Issue Template: Batch email request form
cal-itp/customer-success pull request #459
Opened 2024-04-10 01:35 UTC by AnthonyRollins

Closes #448 

## This PR
Adds a new issue template file for batch email requests from the CS team.

## Outstanding items
- Fix an issue with `checkboxes` type not allowing for `validations: required: True`
- Determine if there should be a question about the audience for the email blast

2024-05-16 00:03 UTC, AnthonyRollins commented
@o-ram This is ready for your review.

2024-05-16 01:30 UTC, o-ram requested changes
A few things I noticed on some questions, but otherwise it's looking good!

2024-05-16 01:30 UTC, o-ram commented on .github/ISSUE_TEMPLATE/batch-email-requests.yml
> +      value: |
I think the question for this part is missing. It should ask the following question and be required to answer.

Is the copy finalized?:
- [ ] Yes
- [ ]  No

2024-05-16 01:30 UTC, o-ram commented on .github/ISSUE_TEMPLATE/batch-email-requests.yml
> +      description: Select all the apply.
small typo, should say "Select all that apply"

2024-05-16 01:30 UTC, o-ram commented on .github/ISSUE_TEMPLATE/batch-email-requests.yml
> +      label: Confirm that the linked document above provides the following pieces of information
Can we make this question required as well?

2024-05-16 22:14 UTC, o-ram commented on .github/ISSUE_TEMPLATE/batch-email-requests.yml
> +      label: Confirm that the linked document above provides the following pieces of information
that's fine, not a huge deal! Should be important enough that people won't skip it.

2024-05-16 23:02 UTC, AnthonyRollins commented
@o-ram I added in some changes, and still need to figure out how to make the `checkboxes` question required.

2024-07-29 20:57 UTC, AnthonyRollins commented
@thekaveman Not sure what the issue is here, but I can't seem to figure out how to make `type: checkboxes` use a `validation` I took a look at the Gihub forums and found a small discussion on this topic: https://github.com/orgs/community/discussions/45084, but no one seems to have an answer on this.

2024-07-30 18:49 UTC, thekaveman commented
> @thekaveman Not sure what the issue is here, but I can't seem to figure out how to make `type: checkboxes` use a `validation` I took a look at the Gihub forums and found a small discussion on this topic: https://github.com/orgs/community/discussions/45084, but no one seems to have an answer on this.

Yeah I'm not seeing much in the way of helpful information in that thread...

@angela-tran @machikoyasuda @lalver1 @allejo is this anything you all have seen / know how to address?

2024-07-30 22:48 UTC, lalver1 commented
I made a test issue template using `checkboxes` and `validations: required: true` and yeah, I see that the `checkboxes` section doesn't get the red asterisk that they are required. A workaround that may help is to mark each `option` with `required: true`. Sort of like:
```
 - type: checkboxes
    id: information
    attributes:
      label: Confirm that the linked document above provides the following pieces of information
      description: Select all that apply.
      options:
        - label: Clear subject line
          required: true
        - label: Pre-header (Optional, this is the line that shows up below the Subject Line in your mobile inbox. If your email has no pre-header, check this box anyway)
        - label: A concise body
        - label: A signature at the end of the body (eg, From, The Cal-ITP Team)
```

It looks like the red asterisk shows up on each `label` and the `Submit new issue` button behaves as expected:

![image](https://github.com/user-attachments/assets/28a64f06-9124-4edb-b098-8220deaf16f6)

2024-07-31 00:26 UTC, AnthonyRollins commented
Thanks, @lalver1, for figuring out a workaround!

2024-07-31 22:17 UTC, AnthonyRollins commented
@o-ram This is ready to publish.

2024-08-05 23:36 UTC, o-ram approved these changes
LGTM! Thanks, everyone!

2024-08-06 23:57 UTC, merged